name: Update FanCode to Public Repo

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate docs files
        run: node scripts/generate-fancode.mjs

      - name: Checkout public repo
        uses: actions/checkout@v4
        with:
          repository: msr-sagor/Fantastic-four
          token: ${{ secrets.PUBLIC_REPO_PAT }}
          path: public-repo

      - name: Copy generated files to public repo
        run: |
          rm -rf public-repo/docs/*
          cp -r docs/* public-repo/docs/

      - name: Commit and push to public repo
        run: |
          cd public-repo
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add docs/

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "Update playlist"
          git push
